std_msgs/Header Header

float64 lambda1
float64 lambda2
float64 lambda3

float64 linearity
float64 planarity
float64 scattering

float64 normal_x
float64 normal_y
float64 normal_z

float64 slope

float64 mean_height
float64 height_std

float64 residual_mean
float64 residual_std

float64 outlier_ratio

unit8 UNKNOWN=0
unit8 FLAT=1
unit8 SLOPE=2
unit8 ROUGH=3
unit8 IRREGULAR=4
unit8 EDGE=5

unit8 terrain_type