std_msgs/Header header

float64[] x 
float64[] y 
float64[] z 

float64[] lambda1
float64[] lambda2
float64[] lambda3

float64[] linearity
float64[] planarity
float64[] scattering

float64[] normal_x
float64[] normal_y
float64[] normal_z

float64[] slope

float64[] mean_height
float64[] height_std

float64[] residual_mean
float64[] residual_std

float64[] outlier_ratio

uint8[] terrain_type

uint32[] point_count
